name: 'test1'

on:
  workflow_dispatch:
  push:
    branches:
     - main
  schedule:
    - cron: '*/30 * * * *'

jobs:

  check-in:
    runs-on: ubuntu-latest
    timeout-minutes: 30         
    steps:
    - uses: actions/checkout@v3

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3

        
    - name: test
      run: |
        python3 main.py 
        
    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        BRANCH_NAME: '' #optional defaults to master

